server:
  port: 8888
  max-http-header-size: 8192
  tomcat:
    basedir: /
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
spring:
  application:
    name: cloud_music
  datasource:
    #    指定数据源的类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rds.tyin.vip:3306/cloud_music?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: tyinzero
  #    druid:
  #      # 初始连接数
  #      initialSize: 5
  #      # 最小连接池数量
  #      minIdle: 10
  #      # 最大连接池数量
  #      maxActive: 20
  #      # 配置获取连接等待超时的时间
  #      maxWait: 60000
  #      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  #      timeBetweenEvictionRunsMillis: 60000
  #      # 配置一个连接在池中最小生存的时间，单位是毫秒
  #      minEvictableIdleTimeMillis: 300000
  #      # 配置一个连接在池中最大生存的时间，单位是毫秒
  #      maxEvictableIdleTimeMillis: 900000
  redis:
    host: redis.tyin.vip
    port: 6379
    password: tyinzero
    connect-timeout: 3000
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: com.tyin.cloud.core.configs.mybatis.logs.CloudMyBatisLog
cloud:
  map:
    key: FTRBZ-TK4CV-GR4PG-U3JFQ-7WHCQ-LSFNU
    secret-key: nqsh444578AIJQDjAIMQkZtLpjvCpuwT
  ok-http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
  api:
    prefix:
      admin: /admin
      client: /client
logging:
  level:
    com.tyin: debug
  file:
    name: /data/logs/cloud-music.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 20
      file-name-pattern: /data/logs/cloud-music.%d{yyyy-MM-dd}.%i.log
springdoc:
  swagger-ui:
    path: /doc.html