server:
  port: 9527
  tomcat:
    basedir: /
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  max-http-request-header-size: 8192
logging:
  file:
    name: /data/logs/server/cloud-music.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 20
      file-name-pattern: /data/logs/server/cloud-music.%d{yyyy-MM-dd}.%i.log
#token:
#    header: Authorization
#    secret: abcdefghijklmnopqrstuvwxyz
#    expireTime: 180
springdoc:
  use-fqn: true
  api-docs:
    resolve-schema-properties: true
    path: /v3/api-docs
  packages-to-scan: com.tyin.server
  swagger-ui:
    path: /doc
    default-model-expand-depth: -1
