server:
  port: 9527
  max-http-header-size: 8192
  tomcat:
    basedir: /
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
logging:
  file:
    name: /data/logs/server/cloud-music.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 20
      file-name-pattern: /data/logs/server/cloud-music.%d{yyyy-MM-dd}.%i.log
#token:
#    header: Authorization
#    secret: abcdefghijklmnopqrstuvwxyz
#    expireTime: 180