cloud:
  ok-http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
  api:
    prefix:
      admin: /admin
      client: /client
spring:
  application:
    name: cloud_music_server
  datasource:
    #    指定数据源的类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tyinzero
    filters: stat
    use-global-data-source-stat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #      # 初始连接数
    #      initialSize: 5
    #      # 最小连接池数量
    #      minIdle: 10
    #      # 最大连接池数量
    #      maxActive: 20
    #      # 配置获取连接等待超时的时间
    #      maxWait: 60000
    #      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #      timeBetweenEvictionRunsMillis: 60000
    #      # 配置一个连接在池中最小生存的时间，单位是毫秒
    #      minEvictableIdleTimeMillis: 300000
    #      # 配置一个连接在池中最大生存的时间，单位是毫秒
    #      maxEvictableIdleTimeMillis: 900000
  redis:
    host: redis.tyin.vip
    port: 6379
    password: tyinzero
    jedis:
      pool:
        max-active: 30
        max-wait: 200
        min-idle: 10
        max-idle: 30
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB