cloud:
  ok-http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
  api:
    prefix:
      admin: /admin
      client: /client
      app: /app
  swagger:
    enable: true
    application-name: ${spring.application.name}
    application-version: 1.0
    application-description: API文档
    try-host: http://localhost:${server.port}
spring:
  application:
    name: cloud_music_server
  datasource:
    #    指定数据源的类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: tyin
        login-password: 123456
        allow:
        enabled: true
      max-wait: 60000
      max-active: 20
      initial-size: 5
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      filters: stat, wall
  redis:
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 500
        min-idle: 5
        max-idle: -1
        max-wait: -1
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis-plus:
  configuration:
    log-impl: com.tyin.core.config.database.mybatis.logs.CloudMyBatisLog
logging:
  level:
    com.tyin: debug